// src/app/layout.js
import React from 'react';
import '/styles/globals.scss'; // Ensure you have a global CSS file or adjust accordingly

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}